#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "lib"))

from walkthrough.cli import main  # noqa: E402

sys.exit(main(sys.argv[1:]))
